### ISSUE TITLE
feat: back to "no scene" status

### ISSUE THREAD

**Issue by lajbel** [marklovers/kaplay#112]
Now, if you create some objects without a scene and create a scene too...

```js
add([
    rect(40, 90),
]);

scene("x", () => {
    add([
        sprite("bean"),
    ]);
});
```

You can go back in the scene as many times as you want with `go("x")`, but you can't back to the scene with the rect.

The API would be like `go("kaplay:root")` or `detachScene()`, something like that

**Comment by amyspark-ng** [comment]
i don't understand....
