### ISSUE TITLE
Outlines don't work on circles

### ISSUE THREAD

**Issue by amyspark-ng** [marklovers/kaplay#12]
Having an object with a circle comp and an outlineComp will not display, the outline, so outlines don't work on circle objects

**Comment by mflerackers** [comment]
Wasn't that fixed in the main branch?

**Comment by mflerackers** [comment]
here https://github.com/marklovers/kaplay/commit/86225da1ef8e1983d76c68b502ffccfc67448baf

**Comment by amyspark-ng** [comment]
Oh im sorry, thought this was still and issue, thank you for informing me
