### ISSUE TITLE
feat: tween styles

### ISSUE THREAD

**Issue by amyspark-ng** [marklovers/kaplay#127]
### A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Tween styles, i wish there was a way to loop a tween

I remember MeowcaTheoRange's tween library having tween styles, could look into it
https://github.com/MeowcaTheoRange/KBTween

**Comment by lajbel** [comment]
you mean the ping pong, reverse and that stuff?

**Comment by amyspark-ng** [comment]
Yeah i think i'll close this because the animate component released, which is a better/more-complex version of a tween, that does have these features, so
