### ISSUE TITLE
fix: Polygons are filled incorrectly

### ISSUE THREAD

**Issue by MeowcaTheoRange** [marklovers/kaplay#139]
## **Describe the bug**
How KAPLAY renders polygons right now can cause concave objects to look strange, due to the fact that KAPLAY renders polygon fill by creating triangles attached to the first point. For convex objects, this is fine, but for complex concave polygons, this can cause overlapping triangles or increased opacity within/outside of the shape, which can usually only be fixed by changing which point is first, or by splitting one polygon up into many different polygons.

## **Version**
KAPLAY 3001.0.0

## **To Reproduce**
1. `add()` a GameObj with a complex concave polygon shape.

## **Expected behavior**
Polygons are filled based on their bounds, maybe with triangles tessellated across the shape to make the final polygon, much like how most 3D objects are created and rendered.

## **Screenshots**
What it looks like now:
![image](https://github.com/marklovers/kaplay/assets/58280776/9cf9471e-ddb9-451f-9904-3fdeeace2b51)
What it renders:
![image](https://github.com/marklovers/kaplay/assets/58280776/ec24b06e-7b05-4a1d-9962-832ad0da8a1c)

What it should look like, achieved by splitting the polygon into multiple and drawing them manually:
![image](https://github.com/marklovers/kaplay/assets/58280776/ec789e16-64fa-43bb-b923-8ee7baf920cc)
What it renders:
![image](https://github.com/marklovers/kaplay/assets/58280776/77881e2e-2a73-4681-a686-a04ab5c79bc6)
What it should ideally render:
![image](https://github.com/marklovers/kaplay/assets/58280776/da3a5d4b-1824-4bed-9a96-93dcf73c609a)

**Comment by mflerackers** [comment]
Kaplay has polygon triangulation, but it is currently behind an experimental triangulate: true flag in the drawPolygon options.
