### ISSUE TITLE
feat: `makeComponent` helper

### ISSUE THREAD

**Issue by lajbel** [marklovers/kaplay#140]
A `makeComponent` helper will help to create strong typed components.

**Example:**

```ts
makeComponent("body", (mass) => {
   return {
      jump() {
          this // type: GameObj<AreaComp> & this
          // ...
      }
   }
}, [area]);
```

**Tasks:**

- [ ] create a "shared" type that can map component types along their id literal string
- [ ] create a `makeComponent` function that adds id and type to that shared type
- [ ] implementation
- [ ] documentation

**Comment by niceEli** [comment]
consitering that this is a plugin it shouldnt be the most difficult thing, you would just need to ask @neverUsedGithub really tbh

**Comment by lajbel** [comment]
is not the same that the plugin, it will incorporate a special type context. You can't simply call the plugin to assert the type

**Comment by niceEli** [comment]
true
