### ISSUE TITLE
feat: unified input system and input bindings

### ISSUE THREAD

**Issue by lajbel** [marklovers/kaplay#142]
2 problems, now you have to hardcode input keys, for example

```js
onKeyPress("space");
```

And also you have to implement two handlers for controllers and keyboard compatibility

```js
onKeyPress("space", jump);
onGamepadButtonPress("dpad-up", jump)
```

So **Write spec**

- [x] unified system of inputs: `onButtonPress("jump")`
- [ ] methods for set and get input bindings `getButton("jump")`, `getButtonByKey("up")`
- [ ] example

**Comment by niceEli** [comment]
a way for detecting inputs would be like this i would think
