### ISSUE TITLE
feat: make fadeOut() use opacity to fade from

### ISSUE THREAD

**Issue by niceEli** [marklovers/kaplay#15]
Change fadeOut to fade from opacity to 0 instead of 1 to 0

**Comment by Princeyadav05** [comment]
Hi @niceEli , can I give this a try? Was able to find the fadeOut method in OpacityComp interface.
I'm sure would be able to solve this your guidance.

**Comment by niceEli** [comment]
sure you can try to solve this issue. I've added you as a assignee so remember to make a pr referencing this issue (#15) when your done. also remember to use conventional commit messages for your pr and commits to keep everything organized [https://www.conventionalcommits.org/en/v1.0.0/](https://www.conventionalcommits.org/en/v1.0.0/)
