### ISSUE TITLE
feat: camFlash()

### ISSUE THREAD

**Issue by amyspark-ng** [marklovers/kaplay#153]
### A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Think it would be cool to have a function to flash the screen, something like `camFlash(WHITE, 1)` being white the color and 1 the time in seconds it takes to fade out, if this could be done using draw i think i would be able to do it :)

**Comment by mflerackers** [comment]
Isn't that just this?
```ts
const flash = add([
  rect(width(), height()),
  color(WHITE),
  opacity()
])
flash.fadeIn(1).onEnd(destroy(flash))
```

**Comment by amyspark-ng** [comment]
well yes, if it's dumb feel free to close the issue

**Comment by mflerackers** [comment]
No, no, you can add it. The framework which shall not be named also has it I think.

**Comment by amyspark-ng** [comment]
oh, good, would it be better to do with draw or game object?

**Comment by mflerackers** [comment]
One extra game object is not going to hurt performance.
