### ISSUE TITLE
fix: layers order should be backwards

### ISSUE THREAD

**Issue by amyspark-ng** [marklovers/kaplay#186]
im currently making layers in my game, and i realized this

```ts
// the one on the bottom is the one that gets rendered first
layers([
	"background",
	"hexagon",
	"ui",
	"windows",
	"powerups",
	"logs",
	"sound",
	"mouse",
], "background")
```

isn't it weird that the one at the bottom of the list (visuallty) is the one that shows up on top of the other sprites?, feel free to close if im just dumb

**Comment by niceEli** [comment]
@mflerackers is this correct or no?

sorry if your sleeping for the ping.

**Comment by amyspark-ng** [comment]
yeah probably not a bug, just thought it was weird

**Comment by mflerackers** [comment]
I'll check it.

**Comment by mflerackers** [comment]
In the layers example there is
```ts
layers(["bg", "game", "ui"], "game");
```
and bg gets drawn first, then game, then ui.

**Comment by amyspark-ng** [comment]
then it's fine, my brain just looked at it weird
