### ISSUE TITLE
feat: Color.mult() takes a "blendFactor" parameter

### ISSUE THREAD

**Issue by amyspark-ng** [marklovers/kaplay#188]
So you can choose how "blended" 2 colors are when adding them to each other

**Comment by mflerackers** [comment]
Isn't that lerp? c1 * a + c2 * (a-1) or c1 + (c2-c1) * a

**Comment by amyspark-ng** [comment]
oh wait, you can pass 2 colors in lerp like this:
`obj.color = lerp(RED, BLUE, 0.5)`
0 being red, 0.5 being the perfect mix and 1 being blue

i do still think it would be a nice feature wouldn't it? not everyone would be able to come up with a solution like this

**Comment by mflerackers** [comment]
But mult multiplies colors, it doesn't add/blend them. It is basically to reduce or mask certain color channels.

**Comment by amyspark-ng** [comment]
Ohhh i think i see what you mean, i just learned that there's a lerp function in the color type, now i feel silly

**Comment by amyspark-ng** [comment]
BLUE.lerp(RED, 0.5) will return purple, problem fixed
