### ISSUE TITLE
bug: pos.dist is not a function under certain circumstances

### ISSUE THREAD

**Issue by RShadowhand** [marklovers/kaplay#197]
## **Describe the bug**

Creating a vec2 from within a function makes pos.dist fail. Passing a vec2 created from a different function works.

## **Version**

v3001

## **To Reproduce**

What works:
```js
const dronePositions = positions.filter(p => p.type == "drone"); // array of { x, y } objects
for(const initialPos of dronePositions){
  map.add(makeDrone(k, k.vec2(initialPos.x, initialPos.y))); // ! make and pass vec2 here
}
```

```js
// k is an instance of kaplay
// initialPos is a vec2 created outside this function
export function makeDrone(k, initialPos){
  const player = k.get('player', {recursive: true})[0]; // player object, exists
  const drone = k.make([
    k.pos(initialPos),
    {
      speed: 100,
      range: 100
    }
  ]);
  drone.onStateUpdate("patrol-right", ()=>{
    if(drone.pos.dist(player.pos) < drone.range){ // ! no problems, no errors, works
      drone.move(drone.speed, 0);
    }
  })
  return drone;
}
```

What doesn't work:
```js
const dronePositions = positions.filter(p => p.type == "drone"); // array of { x, y } objects
for(const initialPos of dronePositions){
  map.add(makeDrone(k, initalPos)); // pass just the object { x, y }, not a vec2
}
```
```js
// k is an instance of kaplay
// initialPos is { x, y } object, not vec2
export function makeDrone(k, initialPos){
  const player = k.get('player', {recursive: true})[0]; // player object, exists
  const drone = k.make([
    k.pos(k.vec2(initialPos.x, initialPos.y)), // create vec2 here
    {
      speed: 100,
      range: 100
    }
  ]);
  drone.onStateUpdate("patrol-right", ()=>{
    if(drone.pos.dist(player.pos) < drone.range){ // ! ERROR: drone.pos.dist is not a function
      drone.move(drone.speed, 0);
    }
  })
  return drone;
}
```

Moreover, I can actually console.log the dist once before it fails and goes to blue screen.

## **Expected behavior**

Setting vec2 in different places shouldn't cause vec2 methods to fail.

**Comment by lajbel** [comment]
Can you do a minimal reproduction? I did this code

```js
kaplay();
loadBean();

const objPos = {
    x: 0,
    y: 100,
};

const x = add([]);

const bean = make([
    sprite("bean"),
    pos(vec2(objPos.x, objPos.y)),
]);

onUpdate(() => {
    console.log(bean.pos.dist(center())); // here should put the error
});

x.add(bean);
```

And I can't see that bug

**Comment by mflerackers** [comment]
You use {x,y} objects, not Vec2 objects, so they don't have the dist method.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RShadowhand** [comment]
> You use {x,y} objects, not Vec2 objects, so they don't have the dist method.

I created the vec2 in the function that gets the { x, y } object in the not-working situation

> Can you do a minimal reproduction? I did this code
> And I can't see that bug

Trying right now to create a minimal project and uploading to github as a repo.

**Comment by RShadowhand** [comment]
Apologies for the confusion. It seems I'm setting initalPos somewhere else as the object, and that's causing the issue for off-screen entities.
