### ISSUE TITLE
bug: custom button binding has default mouse input set if the name "left" is used

### ISSUE THREAD

**Issue by JSLegendDev** [marklovers/kaplay#254]
If you use the new custom binding feature of kaplay 3001 and use the name "left" as a button, the mouse input will be set to left by default.

This is an issue because if you want to make the player move left when using the keyboard or gamepad you don't want the player to move left if they left-click their mouse.

Version where this issue is noticed : 3001.0.0-alpha.17
To reproduce :

```javascript
kaplay({
buttons: {
    left: {
      keyboard: ["left", "a"],
      gamepad: ["south"],
    },
  },
})

onButtonDown("left", () => {
    console.log("this shouldn't appear when left-clicking the mouse but it does")
});
```

**Comment by lajbel** [comment]
oh, will fix!
