### ISSUE TITLE
Vite compile error with KaPlay ( "ReferenceError: Nh is not defined" )

### ISSUE THREAD

**Issue by BananaAcid** [marklovers/kaplay#259]
### After vite compiling the TS, for KaPlay and original KaboomJS, some Var is not defined.

Trying to integrate an animation into nuxt3.

`nuxi dev` works where it will NOT compile all TS into one file, but running the compiled .dist/server.mjs after `nuxi build` does not, where vite compiled all TS.

### What version are you running?

"kaplay": "^3001.0.0-alpha.17",

and

"kaboom": "^3000.1.17",

### Steps to reproduce the behavior:

1. create a nuxt project
2. integrate KaPlay wich initializes a blank canvas.

## **Result**

```
ReferenceError: Nh is not defined
    at kaplay (kaboom.mjs:53:13066)
    at Ih (main.ts:28:12)
    at Proxy.mounted (index.vue:21:26)
    at runtime-core.esm-bundler.js:1808:40
    at _t (runtime-core.esm-bundler.js:195:19)
    at je (runtime-core.esm-bundler.js:202:17)
    at Rr.t.__weh.t.__weh (runtime-core.esm-bundler.js:1788:19)
    at sr (runtime-core.esm-bundler.js:379:35)
    at gl (runtime-core.esm-bundler.js:415:5)
```

main.ts:28:12
```
	const k = kaboom();
```

Test Source-Code and Test:

https://codesandbox.io/p/devbox/nuxt-kaplay-kaboomjs-c6fr54

--- 

Additionally: Always error (no dev and no build)

using

```ts
import kaplay from "./node_modules/kaplay/src/kaboom";
```

and

```ts
const KAPLAY = kaplay({global: false});
```

it errors out with: 

    DvcSRt4K.js:18 [nuxt] error caught during app initialization 
    TypeError: Cannot read properties of undefined (reading 'slice')
        at DvcSRt4K.js:69:42838
        at D0 (DvcSRt4K.js:69:42952)
        at Proxy.mounted (DvcSRt4K.js:72:7672)
        at DvcSRt4K.js:14:10066
        at Sn (DvcSRt4K.js:14:38)
        at Wt (DvcSRt4K.js:14:109)
        at e.__weh.e.__weh (DvcSRt4K.js:14:9946)
        at Pr (DvcSRt4K.js:14:1548)
        at d (DvcSRt4K.js:14:22797)
        at mount (DvcSRt4K.js:14:17796)

at:

    const X = (()=>{
        const o = new (window.AudioContext || window.webkitAudioContext)
          , h = o.createGain();
        h.connect(o.destination);
        const p = new S(L0(o));
       return o.decodeAudioData(C0.buffer.slice(0)).then(v=>{    //   <--------
            p.buf = v
        }
        ).catch(v=>{
            console.error("Failed to load burp: ", v)
        }

**Comment by lajbel** [comment]
investigating, maybe is a minification error, maybe https://github.com/terser/terser would work?

**Comment by BananaAcid** [comment]
@lajbel : I don't know, there seems to be no option for a Nuxt3 project to select terser when setting it up.

**Comment by lajbel** [comment]
> @lajbel : I don't know, there seems to be no option for a Nuxt3 project to select terser when setting it up.

Would you try the latest alpha 18? npm i kaplay@3001.0.0-alpha.18

**Comment by BananaAcid** [comment]
Hehe, just tried and while reporting back, I saw your post :)

The new build works. Updated the CodeSandbox/Readme.md as well as https://gist.github.com/BananaAcid/9f7bb09b8fc6efffc2f8520e4316e5c2 (where I was collecting my workarounds for VUE3 / Nuxt3 )
