### ISSUE TITLE
feat: make gravity scale a vector to change gravity direction at runtime

### ISSUE THREAD

**Issue by amyspark-ng** [marklovers/kaplay#40]
> Would it be possible to implement a system where the gravity for body() components changes direction at runtime? (https://github.com/replit/kaboom/issues/575)

Was in the original kaboom issues tab, thought it was still relevant, so it might be a nice feature

_Originally posted by @amyspark-ng in https://github.com/marklovers/kaplay/discussions/39_

**Comment by amyspark-ng** [comment]
`isGrounded() won't work if the gravity is negative #689`
https://github.com/replit/kaboom/issues/689

i don't know if this was fixed but might still be relevant

Also got me thinking on maybe creating a different function for body component called addForce, where it's like jump, but you can also set horizontal force applied?

**Comment by mflerackers** [comment]
I'll add it once I refactor gravity. I'll add applyForce and applyImpulse.

**Comment by mflerackers** [comment]
Right now there are tests like

```ts
isFalling(): boolean {
  return this.vel.y > 0
},

isJumping(): boolean {
  return this.vel.y < 0
},
```

These need to become

```ts
isFalling(): boolean {
  return this.vel.dot(gravity) > 0 // Same direction as gravity
},

isJumping(): boolean {
  return this.vel.dot(gravity) < 0 // Opposite direction as gravity
},
```
