### ISSUE TITLE
feat: upgrade get

### ISSUE THREAD

**Issue by mflerackers** [marklovers/kaplay#44]

**Comment by mflerackers** [comment]
Currently get only takes the tag or tags objects need to have in order to be returned. There is also an optional recursive flag to return descendants instead of children.
This is quite limited.
The new get would takes an option struct:
```ts
type GetOpt {
  include?: string[]
  exclude?: string[]
  distance?: number
  visible?: boolean
  hierarchy?: "children" | "siblings" | "ancestors" | "descendants"
}
```
This allows the user to do inclusive and exclusive queries, look for nearby or far away objects, look for visible or invisible objects and have more control over where to search in the hierarchy.
It also allows use to speed up these operations (caching, quadtree, etc) and have users enjoy these optimisations immediately without changes to their code.

**Comment by niceEli** [comment]
This would be useful to have

**Comment by amyspark-ng** [comment]
Wouldn't the title be update get? Thought it was confusing

**Comment by amyspark-ng** [comment]
> Wouldn't the title be update get? Thought it was confusing

upgrade was right idk what was i on
