### ISSUE TITLE
feat: key to change debug

### ISSUE THREAD

**Issue by amyspark-ng** [marklovers/kaplay#46]
**Is your feature request related to a problem? Please describe.**
- Some browsers have have actions when pressing F1 and you can't change them (ex: Microsoft Edge)

**Describe the solution you'd like**
- Maybe add a property on the StartGame() function where you can set the key you'd want to press when opening debug

**Additional context**
- I could maybe work on it, doesn't seem to complex :) maybe also a onInspect, that'd be nice

**Comment by niceEli** [comment]
This seems like a useful change. I didn't even know F1 enabled debug
