### ISSUE TITLE
fix: cannot create kaplay or kaboom project in Windows 10bug: your bug here

### ISSUE THREAD

**Issue by markwen** [marklovers/kaplay#78]
First, I am a big fan of kaplay or kaboom library. It's brilliant for beginners. However, I have big problem in creating kaplay or kaboom projects under windows 10. Please see below:

**Software version:**
Node.js v20.13.1
npm 10.8.0
Python 3.12.3

Error message under Windows 10 command line:

E:\projects>**npx create-kaplay mygame**
Need to install the following packages:
create-kaplay@2.6.0
Ok to proceed? (y) y

creating E:\projects\mygame/package.json
creating E:\projects\mygame\www/index.html
creating E:\projects\mygame\src/main.js
creating E:\projects\mygame/README.md
creating E:\projects\mygame/.gitignore
creating E:\projects\mygame/README.md
downloading default sprites
installing packages "kaplay@latest"
node:internal/child_process:421
throw new ErrnoException(err, 'spawn');
^
Error: spawn EINVAL
at ChildProcess.spawn (node:internal/child_process:421:11)
at Object.spawn (node:child_process:761:9)
at file:///C:/Users/mark-xps/AppData/Local/npm-cache/_npx/f1d948c33646a2cb/node_modules/create-kaplay/create.js:162:25
at new Promise ()
at exec (file:///C:/Users/mark-xps/AppData/Local/npm-cache/_npx/f1d948c33646a2cb/node_modules/create-kaplay/create.js:161:5)
at file:///C:/Users/mark-xps/AppData/Local/npm-cache/npx/f1d948c33646a2cb/node_modules/create-kaplay/create.js:383:7
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
errno: -4071,
code: 'EINVAL',
syscall: 'spawn'
}

Similar things happened when creating kaboom projects in Windows 10. I am not sure what is happening. Since most of PC users have Windows 10 as the primary OS, this is quite disappointing. Can this be resolved in a short time?

Thanks very much

**Comment by lajbel** [comment]
Fixed, update to `create-kaplay@2.6.3` :)

**Comment by markwen** [comment]
thanks so much for fixing it so quickly. you rock!
