### ISSUE TITLE
feat: radius on individual corners

### ISSUE THREAD

**Issue by amyspark-ng** [marklovers/kaplay#85]
## **Is your feature request related to a problem? Please describe.**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
I wish you could add an individual radius on each corner of a rect

## **Describe the solution you'd like**A clear and concise description of what you want to happen.
Maybe do something like rect(100, 100, [10, 5, 5, 10]) where it takes an array of numbers which could be the radius of each individual corner

**Comment by mflerackers** [comment]
That would be rect(100, 100, {radius:[10, 5, 5, 10]})

**Comment by mflerackers** [comment]
It is fairly easy to add, but there's a potential problem. Polygon also has radius. seems the plan was to have polygons with round corners. If I make radius: number | number[], I need to make it the same for Polygon (they're related). Since Polygon doesn't use it, it might be OK though.

**Comment by lajbel** [comment]
added on #87

**Comment by amyspark-ng** [comment]
that was FAST
